version: '3.8'

services:
  db:
    image: mysql:8
    container_name: impacto_db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: impacto
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: impacto_app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/impacto
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - db

volumes:
  mysql_data:
